version: '3.9'

services:
  mysql-database:
    image: mysql:latest
    container_name: mysql-database
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - comuni-db:/var/lib/mysql

  api-comuni-italiani:
    image: antoninobonanno/api-comuni-italiani:latest
    container_name: api-comuni-italiani
    restart: always
    environment:
      - TZ=Europe/Rome
      - APP_PORT=${APP_PORT}
      - DATABASE_URL=mysql://${DB_USERNAME}:${DB_PASSWORD}@mysql-database:3306/${DB_DATABASE}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mysql-database
    links:
      - mysql-database

volumes:
  comuni-db:
